### ISSUE TITLE
Doesn't work with transform-object-rest-spread

### ISSUE THREAD

**Issue by olalonde** [jhen0409/babel-preset-es2015-node6#2]
Anyone managed to get this preset to work with https://babeljs.io/docs/plugins/transform-object-rest-spread/? 

Seems it works fine for spread but doesn't work for rest. I'm guessing I need to install an additional preset. Reported here as well: https://phabricator.babeljs.io/T7316

**Comment by olalonde** [comment]
Think I got it to work with:

``` javascript
{
  "presets": ["es2015-node6"],
  "plugins": [
    "babel-plugin-transform-es2015-destructuring",
    "transform-object-rest-spread"
  ]
}
```

**Comment by jhen0409** [comment]
You're right, I'll add back `transform-es2015-destructuring`, until this issue is resolved.

Keep this issue open. :)

**Comment by ssova-4xxi** [comment]
Node.js@6 has destructing support!
http://node.green

**Comment by olalonde** [comment]
@ss4xxi it does... The issue is that `transform-object-rest-spread` doesn't work without `transform-es2015-destructuring` for some reason.

**Comment by jhen0409** [comment]
This [playground](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=stage-2&code=let%20%7B%20x%2C%20y%2C%20...z%20%7D%20%3D%20%7B%20x%3A%201%2C%20y%3A%202%2C%20a%3A%203%2C%20b%3A%204%20%7D%3B) can simply reproduce the problem. Also I commented on [T7316](https://phabricator.babeljs.io/T7316#77771).

I'll try to fix it this week.

**Comment by olalonde** [comment]
@jhen0409 thanks :)

**Comment by jhen0409** [comment]
Now [T7316](https://phabricator.babeljs.io/T7316) is merged to [T7086](https://phabricator.babeljs.io/T7086).

It looks `transform-es2015-parameters` is also required, maybe we can split to new file, use `es2015-node6/object-rest` as a short-term solution?

**_UPDATED_** I splitted `destructuring`, `parameters` to `es2015-node6/object-rest` on v0.2.0, or you can still use v0.1.

**Comment by hzoo** [comment]
Object rest spread depends on destructuring so we would have to rewrite it to be independent of it

**Comment by antitoxic** [comment]
What's preventing this issue from being closed?

**Comment by olalonde** [comment]
Probably because Babel still requires additional plugins for object rest spread to work (https://github.com/babel/babel/issues/4074),  `babel-plugin-transform-es2015-destructuring` and  `babel-plugin-transform-es2015-parameters` which are otherwise not required for Node v6.

**Comment by Billy-** [comment]
After many hours searching for info and lots of trial and error, I have tried every combination of plugins and presets possible, yet none of them have worked. Can someone please confirm a set up that works? I am compiling for the browser and am running webpack in Node V6.2.2

**Comment by antitoxic** [comment]
@Billy-  Use `es2015` for browser bundle and `es2015-node6/object-rest` for node.

**Comment by Billy-** [comment]
As I said, I have tried every combination of plugins and presets I have come across. My most recent babelrc file contains es2015 preset (and react), transform-es2015-destructuring and transform-object-rest-spread plugins.

**Comment by olalonde** [comment]
Can you share your .babelrc file and what parsing error you are getting? I'm using:

``` javascript
{
  "presets": ["eslatest-node6"],
  "plugins": [
    "transform-es2015-destructuring",
    "transform-es2015-parameters",
    ["transform-object-rest-spread", { "useBuiltIns": true }]
  ]
}
```

**Comment by Billy-** [comment]
Sorry guys, false alarm.. Not sure what was going on at work earlier. Pulled down my WIP and it worked :angry:. I reduced down my .babelrc and it actually works with only the object rest spread transform plugin:

```
{
  "presets": [
    "es2015",
    "react"
  ],
  "plugins": [
    "transform-object-rest-spread"
  ]
}
```

Will try to replicate the issue at work on Monday...

**Comment by dtothefp** [comment]
https://github.com/build-boiler/build-boiler/blob/master/packages/boiler-config-babelrc/node-6.json

**Comment by ahmed1490** [comment]
trying to get it working for node..

```
    "babel-plugin-transform-es2015-destructuring": "^6.18.0",
    "babel-plugin-transform-object-rest-spread": "^6.16.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-stage-0": "^6.16.0",
    "babel-register": "^6.18.0",
```

```
{
  "presets": ["es2015", "stage-0"],
  "plugins": ["transform-es2015-destructuring", "transform-object-rest-spread"]
}
```

and it still complains Syntax Error

**Comment by klimashkin** [comment]
https://github.com/babel/babel/releases/tag/v6.19.0
"Make the plugin work standalone with parameters/destructuring plugins"

**Comment by hzoo** [comment]
Yep it should work now without the 2 plugins!

**Comment by deadbeef84** [comment]
@hzoo can you confirm this is actually working? I'm using `"presets": ["es2015-node6", "stage-0"]` but still get `SyntaxError: Unexpected token ...`. It's working as expected with es2015-node6/object-rest. I've confirmed that babel-plugin-transform-object-rest-spread@6.19.0 is installed.

**Comment by christophehurpeau** [comment]
@deadbeef84 can be related: https://github.com/babel/babel/pull/4883

**Comment by hzoo** [comment]
> can you confirm this is actually working

You can test in the repl - it would be useful you can post the relevant code too. The transform basically had to be rewritten for rest so it's likely some cases were missed.

**Comment by juanpaco** [comment]
I love babel, and thanks for the work on it!

I'm coming across a similar error.  I was following https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters#Destructuring_rest_parameters, and in Babel, I'm unable to get either of the following to work (SyntaxError is the result):

```
function foo(a, b, ...[ c, d ]) { }
function foo(...[ c, d ]) { }
```

I don't know if those are intended to work with the solo object rest spread plugin.  I'm running babel-plugin-transform-object-rest-spread@6.20.2.

**Comment by olalonde** [comment]
@juanpaco I think it's this bug: https://github.com/babel/babel/issues/4851  .. work around is to "use   the parameter/destructuring transforms until it's fixed".

**Comment by klimashkin** [comment]
Since Babel 6.22 `transform-object-rest-spread` works fine finally, there is no need to use `es2015-node6/object-rest` preset anymore, just `es2015-node6` is quite enough.

I think this issue and #4 can be closed
